### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by elpekenin** [joelspadin/zmk-cli#2]
Feel free to ignore, just a few things after minimal walkthrough over the codebase locally
- Some type hints are wrong: `def function(arg: type = None)` should be `def function(arg: type | None = None)`
- I noted a couple of `# pylint: disable` lines, but pylint is (as far as i can tell) not mentioned anywhere... Might have forgotten to add it as a pre-commit hook?
- Add a mypy (or pyright?) hook for static type checking? (mypy currently complains about quite a few things)
- Use ruff instead of isort+black? It can do both formatting and linting and has a lot of checks (by default, most aren't enabled, though)
- Might be interesting to add some way for updating `zmk-cli` (or at least, check for updates), specially at the current stage where code is far from stable and testers should be using latest version for useful feedback. Doing it automatically (say, every X times user runs `zmk`) sounds too aggresive, but a subcommand could be nice and easy to develop

**Comment by joelspadin** [comment]
So far, I've just been using the pylint/black/isort integration with VS Code. I haven't set up any CI checks for them, but that would be good to add. (The default type checking is not very thorough either.)

I don't think there should be a subcommand for updating ZMK CLI, since that's what pip(x) is for. A periodic version check on startup that prints a message if a newer version is available could be useful though, as long as there's a setting to disable it.

**Comment by joelspadin** [comment]
Transferred to https://github.com/zmkfirmware/zmk-cli/issues/2 and https://github.com/zmkfirmware/zmk-cli/issues/3
